In [2]:
import numpy as np
import pandas as  pd
import matplotlib.pyplot as plot
import seaborn as sns
import os

In [3]:
os.getcwd()

'C:\\Users\\vksk0'

In [24]:
os.chdir('F:\\Vikas\\codebasics exercise\\py-master')

In [54]:
df = pd.read_csv('F:\\Vikas\\codebasics exercise\\py-master\\ML\\18_PCA\\Exercise\\heart.csv')

In [61]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [103]:
df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [105]:
cols = ['Age', 'RestingBP','Cholesterol','FastingBS','MaxHR','Oldpeak','HeartDisease'] # one or more

Q1 = df[cols].quantile(0.25)
Q3 = df[cols].quantile(0.75)
IQR = Q3 - Q1

df = df[~((df[cols] < (Q1 - 1.5 * IQR)) |(df[cols] > (Q3 + 1.5 * IQR))).any(axis=1)]

In [106]:
X_new = df.iloc[:,:-1]
Y = df.iloc[:,-1]

In [107]:
X_new.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up

In [108]:
Y.head()

0    0
1    1
2    0
3    1
4    0
Name: HeartDisease, dtype: int64

In [109]:
X = pd.get_dummies(X_new, columns = ['Sex', 'ChestPainType','RestingECG','ExerciseAngina','ST_Slope'])
print(X)

     Age  RestingBP  Cholesterol  FastingBS  MaxHR  Oldpeak  Sex_F  Sex_M  \
0     40        140          289          0    172      0.0      0      1
1     49        160          180          0    156      1.0      1      0
2     37        130          283          0     98      0.0      0      1
3     48        138          214          0    108      1.5      1      0
4     54        150          195          0    122      0.0      0      1
5     39        120          339          0    170      0.0      0      1
6     45        130          237          0    170      0.0      1      0
7     54        110          208          0    142      0.0      0      1
8     37        140          207          0    130      1.5      0      1
9     48        120          284          0    120      0.0      1      0
10    37        130          211          0    142      0.0      1      0
11    58        136          164          0     99      2.0      0      1
12    39        120          204          0    145      0.0      0      1
13    49        140          234          0    140      1.0      0      1
14    42        115          211          0    137      0.0      1      0
15    54        120          273          0    150      1.5      1      0
16    38        110          196          0    166      0.0      0      1
17    43        120          201          0    165      0.0      1      0
18    60        100          248          0    125      1.0      0      1
19    36        120          267          0    160      3.0      0      1
20    43        100          223          0    142      0.0      1      0
21    44        120          184          0    142      1.0      0      1
22    49        124          201          0    164      0.0      1      0
23    44        150          288          0    150      3.0      0      1
24    40        130          215          0    138      0.0      0      1
25    36        130          209          0    178      0.0      0      1
26    53        124          260          0    112      3.0      0      1
27    52        120          284          0    118      0.0      0      1
29    51        125          188          0    145      0.0      0      1
31    56        130          167          0    114      0.0      0      1
..   ...        ...          ...        ...    ...      ...    ...    ...
881   44        120          263          0    173      0.0      0      1
882   56        140          294          0    153      1.3      1      0
883   57        140          192          0    148      0.4      0      1
884   67        160          286          0    108      1.5      0      1
885   53        128          216          0    115      0.0      1      0
886   52        138          223          0    169      0.0      0      1
889   59        134          204          0    162      0.8      0      1
890   64        170          227          0    155      0.6      0      1
891   66        146          278          0    152      0.0      1      0
892   39        138          220          0    152      0.0      1      0
893   57        154          232          0    164      0.0      0      1
894   58        130          197          0    131      0.6      1      0
895   57        110          335          0    143      3.0      0      1
896   47        130          253          0    179      0.0      0      1
897   55        128          205          0    130      2.0      1      0
898   35        122          192          0    174      0.0      0      1
899   61        148          203          0    161      0.0      0      1
902   58        125          220          0    144      0.4      0      1
903   56        130          221          0    163      0.0      0      1
904   56        120          240          0    169      0.0      0      1
905   67        152          212          0    150      0.8      0      1
906   55        132          342          0    166      1.2      1      0
907   44        120          169          0    144      2.8      0      1
909   63        124          197          0    136      0.0      1      0
910   41        120          157          0    182      0.0      0      1
912   57        140          241          0    123      0.2      1      0
913   45        110          264          0    132      1.2      0      1
915   57        130          131          0    115      1.2      0      1
916   57        130          236          0    174      0.0      1      0
917   38        138          175          0    173      0.0      0      1

     ChestPainType_ASY  ChestPainType_ATA  ChestPainType_NAP  \
0                    0                  1                  0
1                    0                  0                  1
2                    0                  1                  0
3                    1                  0                  0
4                    0                  0                  1
5                    0                  0                  1
6                    0                  1                  0
7                    0                  1                  0
8                    1                  0                  0
9                    0                  1                  0
10                   0                  0                  1
11                   0                  1                  0
12                   0                  1                  0
13                   1                  0                  0
14                   0                  0                  1
15                   0                  1                  0
16                   1                  0                  0
17                   0                  1                  0
18                   1                  0                  0
19                   0                  1                  0
20                   0                  0                  0
21                   0                  1                  0
22                   0                  1                  0
23                   0                  1                  0
24                   0                  0                  1
25                   0                  0                  1
26                   1                  0                  0
27                   0                  1                  0
29                   0                  1                  0
31                   0                  0                  1
..                 ...                ...                ...
881                  0                  1                  0
882                  0                  1                  0
883                  1                  0                  0
884                  1                  0                  0
885                  0                  0                  1
886                  0                  0                  1
889                  0                  0                  0
890                  0                  0                  0
891                  0                  0                  1
892                  0                  0                  1
893                  0                  1                  0
894                  1                  0                  0
895                  1                  0                  0
896                  0                  0                  1
897                  1                  0                  0
898                  0                  1                  0
899                  1                  0                  0
902                  0                  1                  0
903                  0                  1                  0
904                  0                  1                  0
905                  0                  0                  1
906                  0                  1                  0
907                  1                  0                  0
909                  1                  0                  0
910                  0                  1                  0
912                  1                  0                  0
913                  0                  0                  0
915                  1                  0                  0
916                  0                  1                  0
917                  0                  0                  1

     ChestPainType_TA  RestingECG_LVH  RestingECG_Normal  RestingECG_ST  \
0                   0               0                  1              0
1                   0               0                  1              0
2                   0               0                  0              1
3                   0               0                  1              0
4                   0               0                  1              0
5                   0               0                  1              0
6                   0               0                  1              0
7                   0               0                  1              0
8                   0               0                  1              0
9                   0               0                  1              0
10                  0               0                  1              0
11                  0               0                  0              1
12                  0               0                  1              0
13                  0               0                  1              0
14                  0               0                  0              1
15                  0               0                  1              0
16                  0               0                  1              0
17                  0               0                  1              0
18                  0               0                  1              0
19                  0               0                  1              0
20                  1               0                  1              0
21                  0               0                  1              0
22                  0               0                  1              0
23                  0               0                  1              0
24                  0               0                  1              0
25                  0               0                  1              0
26                  0               0                  0              1
27                  0               0                  1              0
29                  0               0                  1              0
31                  0               0                  1              0
..                ...             ...                ...            ...
881                 0               0                  1              0
882                 0               1                  0              0
883                 0               0                  1              0
884                 0               1                  0              0
885                 0               1                  0              0
886                 0               0                  1              0
889                 1               0                  1              0
890                 1               1                  0              0
891                 0               1                  0              0
892                 0               0                  1              0
893                 0               1                  0              0
894                 0               0                  1              0
895                 0               0                  1              0
896                 0               0                  1              0
897                 0               0                  0              1
898                 0               0                  1              0
899                 0               0                  1              0
902                 0               0                  1              0
903                 0               1                  0              0
904                 0               0                  1              0
905                 0               1                  0              0
906                 0               0                  1              0
907                 0               0                  1              0
909                 0               0                  1              0
910                 0               0                  1              0
912                 0               0                  1              0
913                 1               0                  1              0
915                 0               0                  1              0
916                 0               1                  0              0
917                 0               0                  1              0

     ExerciseAngina_N  ExerciseAngina_Y  ST_Slope_Down  ST_Slope_Flat  \
0                   1                 0              0              0
1                   1                 0              0              1
2                   1                 0              0              0
3                   0                 1              0              1
4                   1                 0              0              0
5                   1                 0              0              0
6                   1                 0              0              0
7                   1                 0              0              0
8                   0                 1              0              1
9                   1                 0              0              0
10                  1                 0              0              0
11                  0                 1              0              1
12                  1                 0              0              0
13                  0                 1              0              1
14                  1                 0              0              0
15                  1                 0              0              1
16                  1                 0              0              1
17                  1                 0              0              0
18                  1                 0              0              1
19                  1                 0              0              1
20                  1                 0              0              0
21                  1                 0              0              1
22                  1                 0              0              0
23                  0                 1              0              1
24                  1                 0              0              0
25                  1                 0              0              0
26                  0                 1              0              1
27                  1                 0              0              0
29                  1                 0              0              0
31                  1                 0              0              0
..                ...               ...            ...            ...
881                 1                 0              0              0
882                 1                 0              0              1
883                 1                 0              0              1
884                 0                 1              0              1
885                 1                 0              0              0
886                 1                 0              0              0
889                 1                 0              0              0
890                 1                 0              0              1
891                 1                 0              0              1
892                 1                 0              0              1
893                 1                 0              0              0
894                 1                 0              0              1
895                 0                 1              0              1
896                 1                 0              0              0
897                 0                 1              0              1
898                 1                 0              0              0
899                 1                 0              0              0
902                 1                 0              0              1
903                 1                 0              0              0
904                 1                 0              1              0
905                 1                 0              0              1
906                 1                 0              0              0
907                 0                 1              1              0
909                 0                 1              0              1
910                 1                 0              0              0
912                 0                 1              0              1
913                 1                 0              0              1
915                 0                 1              0              1
916                 1                 0              0              1
917                 1                 0              0              0

     ST_Slope_Up
0              1
1              0
2              1
3              0
4              1
5              1
6              1
7              1
8              0
9              1
10             1
11             0
12             1
13             0
14             1
15             0
16             0
17             1
18             0
19             0
20             1
21             0
22             1
23             0
24             1
25             1
26             0
27             1
29             1
31             1
..           ...
881            1
882            0
883            0
884            0
885            1
886            1
889            1
890            0
891            0
892            0
893            1
894            0
895            0
896            1
897            0
898            1
899            1
902            0
903            1
904            0
905            0
906            1
907            0
909            0
910            1
912            0
913            0
915            0
916            0
917            1

[588 rows x 20 columns]

# Scaling

In [110]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

C:\Users\vksk0\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\vksk0\Anaconda3\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)

array([[-1.2295279 ,  0.63209752,  0.9850081 , ..., -0.20176215,
        -0.89957255,  0.97314946],
       [-0.28557583,  1.94566296, -1.16508859, ..., -0.20176215,
         1.11163908, -1.02759139],
       [-1.54417859, -0.0246852 ,  0.86665415, ..., -0.20176215,
        -0.89957255,  0.97314946],
       ...,
       [ 0.55349269, -0.0246852 , -2.13164582, ..., -0.20176215,
         1.11163908, -1.02759139],
       [ 0.55349269, -0.0246852 , -0.06045176, ..., -0.20176215,
         1.11163908, -1.02759139],
       [-1.43929503,  0.50074098, -1.26371688, ..., -0.20176215,
        -0.89957255,  0.97314946]])

In [111]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_scaled, Y, test_size=0.2, random_state=30)

In [112]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)
model.score(X_test, y_test)

C:\Users\vksk0\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

0.9322033898305084

In [113]:
from sklearn.decomposition import PCA

pca = PCA(0.95)
X_pca = pca.fit_transform(X)
X_pca.shape

(588, 3)

In [114]:
pca.explained_variance_ratio_

array([0.73969532, 0.17304871, 0.06589364])

In [115]:
X_train_pca, X_test_pca, y_train, y_test = train_test_split(X_pca, Y, test_size=0.2, random_state=30)

In [116]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train_pca, y_train)
model.score(X_test_pca, y_test)

C:\Users\vksk0\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

0.8050847457627118